---
version: 2

deployment:
  name: Live Chat Web (QA)
  source-plan: SNS-FEB0

release-naming:
  next-version-name: qa-1
  auto-increment: true

environments:
  - QA (Global)

QA (Global):
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download
    - script: |
        #!/bin/bash
        set -e
        echo "Ansible Deploy"
        /opt/deployments/bamboo_scripts/deploy.sh live-chat-web global qa
        echo "done"
